### ISSUE TITLE
Approximate timeline for posting other projects?

### ISSUE THREAD

**Issue by zlijingtao** [EasyFL-AI/EasyFL#4]
Hi, I am so impressed with your EasyFL framework and related projects. Do you have a timeline for posting other projects? Thanks!

**Comment by weimingwill** [comment]
Hi, we don't have a specific timeline now, but we will release them gradually in months. May I know which project you are most interested in? Thank you.

**Comment by zlijingtao** [comment]
Thank you so much for your reply. I am particularly interested in "Divergence-aware Federated Self-Supervised Learning". Congrats on its acceptance by ICLR, It is very good work and the experiments are comprehensive. Since my ongoing research project is also on SSL & FL, I would like to check out your implementation and possibly build my own stuff on top of EasyFL framework. 

I can catch up on time if it can be released in one month, Thanks!

**Comment by weimingwill** [comment]
@zlijingtao We have just released it. You can check it out here https://github.com/EasyFL-AI/EasyFL/tree/master/applications/fedssl
